version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  cicd-tests:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: npm --prefix ./backend/ install
      - run:
          name: Install frontend dependencies
          command: npm --prefix ./frontend/ install
      - save_cache:
          paths:
            - backend/node_modules
            - frontend/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Start backend
          command: npm --prefix ./backend/ start
          background: true
      - run:
          name: Start frontend
          command: npm --prefix ./frontend/ start
          background: true
      - run:
          name: waiting for servers
          command: sleep 20
      - run:
          name: Run all tests
          command: npm --prefix ./frontend/ run test

workflows:
  sample:
    jobs:
      - cicd-tests
