version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  cicd-tests-and-lint:
    docker:
      - image: circleci/node:16.10-browsers
        environment:
          DOCKER_BUILDKIT: 1
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install backend dependencies
          command: npm --prefix ./backend/ install
      - run:
          name: Run backend
          command: npm --prefix ./backend/ start
          background: true
      - run:
          name: Install frontend dependencies
          command: npm --prefix ./frontend/ install
      - run:
          name: Run frontend
          command: npm --prefix ./frontend/ start
          background: true
      - run:
          name: Wait for backend and frontend to be ready
          command: sleep 60
      - run:
          name: Run all tests
          command: |
            npm --prefix ./frontend/ run test

      - run: 
          name: delete objects
          command: |
            npm --prefix ./frontend/ run delete

workflows:
  version: 2
  build_and_test:
    jobs:
      - cicd-tests-and-lint
      - delete-objects:
          requires:
            - cicd-tests-and-lint
