version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  cicd-tests-and-lint:
    docker:
      - image: circleci/node:16.10-browsers
        environment:
          DOCKER_BUILDKIT: 1
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install backend folder 
          command: npm --prefix ./backend/ install
      - run:
          name: run backend
          command: npm --prefix ./backend/ start
          background: true
      - run:
          name: install frontend folder 
          command: npm --prefix ./frontend/ install
      - run:
          name: run frontend
          command: npm --prefix ./frontend/ start
          background: true
      - run:
          name: wait for backend and frontend to be ready
          command: sleep 60 
      - run:
          name: run all tests
          command: |
            npm --prefix ./frontend/  run test

workflows:
  sample:
    jobs:
      - cicd-tests-and-lint
